// Nilda plugin contract v2 (SPEC_98). The single source of truth for the Core<->plugin gRPC wire.
//
// Versioning: this contract is carried by plugin-sdk (semver) and guarded by the go-plugin handshake
// ProtocolVersion (Terraform-style) — an incompatible plugin is rejected at load, never silently
// broken. Within a version, fields are only ever ADDED (proto3 forward compatibility); a breaking
// change ships a new package, which is what v2 is.
//
// WHAT CHANGED IN v2, and why it is worth a breaking change: v1's HostService carried five read
// methods and no way to write anything, so a plugin could read a page by slug and list a content type
// and nothing else. No shop could create a product, no importer could create a post — not because
// out-of-process plugins are limited, but because that hand-picked subset was all anything had wired.
// Meanwhile Core has a complete API. v2 removes the subset and hands the plugin a scoped token onto
// that API instead.
//
// The resulting rule is worth stating plainly, because it is the shape of the whole system:
//
//     gRPC is how Core calls the plugin.  HTTP is how the plugin calls Core.
//
// Direction 1 — PluginService (Core -> plugin): lifecycle + hook/event dispatch. Every call is made
// with the per-call timeout (PLUGIN_CALL_TIMEOUT); a slow plugin fails the CALL, never Core.
// Direction 2 — HostService (plugin -> Core, over the go-plugin GRPCBroker): what genuinely belongs on
// this transport — the plugin's own KV namespace and event emission. Capability-enforced server-side
// (deny-by-default); the broker connection belongs to exactly one plugin, so its identity is ambient
// and unforgeable. Data access is not here; it is the API token in InitRequest.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: contract/plugin.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PluginKey           string                 `protobuf:"bytes,1,opt,name=plugin_key,json=pluginKey,proto3" json:"plugin_key,omitempty"`                               // the manifest key (also schema/KV slug)
	NildaVersion        string                 `protobuf:"bytes,2,opt,name=nilda_version,json=nildaVersion,proto3" json:"nilda_version,omitempty"`                      // the running Core version
	GrantedCapabilities []string               `protobuf:"bytes,3,rep,name=granted_capabilities,json=grantedCapabilities,proto3" json:"granted_capabilities,omitempty"` // deny-by-default: only these are callable
	DatastoreDsn        string                 `protobuf:"bytes,4,opt,name=datastore_dsn,json=datastoreDsn,proto3" json:"datastore_dsn,omitempty"`                      // scoped least-privilege DSN; empty unless `datastore`
	KvNamespace         string                 `protobuf:"bytes,5,opt,name=kv_namespace,json=kvNamespace,proto3" json:"kv_namespace,omitempty"`                         // informational (KV ops go through HostService)
	HostBrokerId        uint32                 `protobuf:"varint,6,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`                   // GRPCBroker stream id serving HostService
	// How the plugin reaches Core's own API. This is the plugin's route to reading and writing real data:
	// gRPC is how Core calls the plugin, HTTP is how the plugin calls Core. Before this existed the plugin
	// side of the contract carried five hand-picked read methods and no way to write anything, so no
	// application-class plugin — a shop, a booking system — could be built at all.
	//
	// The token is scoped from the granted capabilities and rotated on every launch, so the only valid
	// credential at any moment is the one held by the process Core just started. Empty when the plugin
	// declared nothing that implies API access.
	ApiBaseUrl string   `protobuf:"bytes,7,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	ApiToken   string   `protobuf:"bytes,8,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	ApiScopes  []string `protobuf:"bytes,9,rep,name=api_scopes,json=apiScopes,proto3" json:"api_scopes,omitempty"` // what the token may attempt, so a plugin can fail fast on its own
	// The values the site owner typed on this plugin's declared admin pages, as a JSON object.
	//
	// JSON rather than map<string,string> because a settings field has a TYPE — a boolean that arrives as
	// "true" and a number that arrives as "5" put the parsing back on every plugin author, and they would
	// each get it slightly wrong.
	//
	// SECRETS ARE IN HERE IN PLAINTEXT, and that is the whole point: the process that has to call the payment
	// gateway is the one that needs the key. It never travels to the browser — the admin screen is told only
	// that a value is configured. The channel is AutoMTLS between Core and a child it just launched.
	//
	// Delivered at Init and never updated in place: Core RESTARTS the plugin when its settings are saved, so
	// a running plugin can never be holding a credential the owner has already replaced.
	SettingsJson []byte `protobuf:"bytes,10,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	// The version this plugin last COMPLETED an Init at, or empty on a fresh install.
	//
	// Adding a column or a table already happens through the manifest declaration — Core applies it on
	// update, additively and idempotently. What this is for is the DATA half: filling a new column from an
	// old one, normalising a stored value, re-keying a row. Without it a plugin could not tell a first run
	// from an upgrade, so a one-time step had to run on every launch or the author had to invent a private
	// version table.
	//
	// Recorded by Core on COMPLETION, so a plugin the supervisor restarts after a crash is told it is running
	// the same version it already initialised at, and the one-time step does not run twice.
	PreviousVersion string `protobuf:"bytes,11,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	// The URL prefix Core reverse-proxies to this plugin, from its manifest ("/sso"). Empty unless `route`
	// was granted.
	//
	// Sent because the proxy forwards the FULL path — a plugin serving "/backchannel-logout" gets a request
	// for "/sso/backchannel-logout" and answers 404. Without this the author has to hard-code the prefix a
	// second time, in Go, matching a manifest nobody will remember to keep in step; the first plugin written
	// against this capability got it wrong exactly that way.
	RoutePrefix   string `protobuf:"bytes,12,opt,name=route_prefix,json=routePrefix,proto3" json:"route_prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_contract_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetPluginKey() string {
	if x != nil {
		return x.PluginKey
	}
	return ""
}

func (x *InitRequest) GetNildaVersion() string {
	if x != nil {
		return x.NildaVersion
	}
	return ""
}

func (x *InitRequest) GetGrantedCapabilities() []string {
	if x != nil {
		return x.GrantedCapabilities
	}
	return nil
}

func (x *InitRequest) GetDatastoreDsn() string {
	if x != nil {
		return x.DatastoreDsn
	}
	return ""
}

func (x *InitRequest) GetKvNamespace() string {
	if x != nil {
		return x.KvNamespace
	}
	return ""
}

func (x *InitRequest) GetHostBrokerId() uint32 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

func (x *InitRequest) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

func (x *InitRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *InitRequest) GetApiScopes() []string {
	if x != nil {
		return x.ApiScopes
	}
	return nil
}

func (x *InitRequest) GetSettingsJson() []byte {
	if x != nil {
		return x.SettingsJson
	}
	return nil
}

func (x *InitRequest) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *InitRequest) GetRoutePrefix() string {
	if x != nil {
		return x.RoutePrefix
	}
	return ""
}

type InitResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RouteAddr string                 `protobuf:"bytes,1,opt,name=route_addr,json=routeAddr,proto3" json:"route_addr,omitempty"` // "host:port" of the plugin's resident HTTP server; empty unless `route`
	Hooks     []string               `protobuf:"bytes,2,rep,name=hooks,proto3" json:"hooks,omitempty"`                          // hook names to receive (requires `hooks` capability)
	Events    []string               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`                        // event types to receive (requires `events` capability)
	// Work Core should run on a schedule and call back for (requires `schedule`). A plugin process is
	// resident and could run its own ticker, but Core-owned scheduling is visible to the site owner,
	// survives a restart, and does not double-fire when a plugin is relaunched.
	Schedules []*Schedule `protobuf:"bytes,4,rep,name=schedules,proto3" json:"schedules,omitempty"`
	// What this plugin can DO, in a form an AI agent can read (requires `abilities`). Core turns each into
	// an ordinary agent tool named "<plugin_key>.<name>", subject to the same connector class ceiling,
	// allowlist and confirmation gates as a built-in one.
	//
	// Without this, the only actions an agent knows about are the ones Core itself ships: a shop plugin
	// could register a product all day and "add these fifty products" had nothing to call.
	Abilities     []*Ability `protobuf:"bytes,5,rep,name=abilities,proto3" json:"abilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_contract_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetRouteAddr() string {
	if x != nil {
		return x.RouteAddr
	}
	return ""
}

func (x *InitResponse) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *InitResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *InitResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *InitResponse) GetAbilities() []*Ability {
	if x != nil {
		return x.Abilities
	}
	return nil
}

// Ability is one action the plugin offers an AI agent.
type Ability struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // lowercase id within the plugin, e.g. "create_product"
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`             // human-readable, for the admin's tool list
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // what the MODEL reads to decide whether this is the right tool — be specific
	// Risk class, matching Core's agent guardrails: read | additive | write | publish | structural |
	// destructive | access | infra. A class Core does not recognise is treated as the MOST restricted one,
	// never the least — so a typo costs an owner one permission click, not an unguarded action.
	Class         string `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	InputSchema   string `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema object describing the arguments; required
	ReadOnly      bool   `protobuf:"varint,6,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`         // advisory MCP annotation; the gates are driven by `class`, not by this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ability) Reset() {
	*x = Ability{}
	mi := &file_contract_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ability) ProtoMessage() {}

func (x *Ability) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ability.ProtoReflect.Descriptor instead.
func (*Ability) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Ability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ability) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Ability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Ability) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Ability) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *Ability) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type Schedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // stable identifier; Core calls back with hook "schedule:<name>"
	Cron          string                 `protobuf:"bytes,2,opt,name=cron,proto3" json:"cron,omitempty"` // standard cron spec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_contract_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Schedule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Schedule) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_contract_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // JSON, possibly modified (filter hooks)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_contract_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HookResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_contract_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *EventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_contract_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{7}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_contract_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_contract_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RevokeIdentityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// provider is your LOCAL key, as declared in your manifest. Core namespaces it.
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// subject is the identity provider's `sub` for the person — the same value your assertion carried.
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// reason is recorded in the audit trail so an administrator reading it later learns WHY somebody was
	// signed out, e.g. "back-channel logout from acme.okta.com".
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeIdentityRequest) Reset() {
	*x = RevokeIdentityRequest{}
	mi := &file_contract_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeIdentityRequest) ProtoMessage() {}

func (x *RevokeIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeIdentityRequest.ProtoReflect.Descriptor instead.
func (*RevokeIdentityRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeIdentityRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *RevokeIdentityRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RevokeIdentityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeIdentityResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sessions_ended is how many were actually revoked. Zero is not an error: the person may simply not
	// have been signed in.
	SessionsEnded int32 `protobuf:"varint,1,opt,name=sessions_ended,json=sessionsEnded,proto3" json:"sessions_ended,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeIdentityResponse) Reset() {
	*x = RevokeIdentityResponse{}
	mi := &file_contract_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeIdentityResponse) ProtoMessage() {}

func (x *RevokeIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeIdentityResponse.ProtoReflect.Descriptor instead.
func (*RevokeIdentityResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeIdentityResponse) GetSessionsEnded() int32 {
	if x != nil {
		return x.SessionsEnded
	}
	return 0
}

type SendEmailRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	To      string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body    string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// lang: a BCP-47-ish language tag ("fa", "ar", "en") the wrapping HTML's dir/lang attributes should
	// carry (Core's own internal/email/direction.go — the fix for KNOWN_ISSUES E-5, "email had no idea
	// which way its text ran", already built for Core's own account mail and now reachable from a plugin
	// too). Empty means no hint: the message renders exactly as it always has.
	Lang          string `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_contract_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_contract_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{13}
}

type KVGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetRequest) Reset() {
	*x = KVGetRequest{}
	mi := &file_contract_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRequest) ProtoMessage() {}

func (x *KVGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRequest.ProtoReflect.Descriptor instead.
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *KVGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetResponse) Reset() {
	*x = KVGetResponse{}
	mi := &file_contract_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetResponse) ProtoMessage() {}

func (x *KVGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetResponse.ProtoReflect.Descriptor instead.
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *KVGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KVGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type KVSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = no expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSetRequest) Reset() {
	*x = KVSetRequest{}
	mi := &file_contract_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetRequest) ProtoMessage() {}

func (x *KVSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetRequest.ProtoReflect.Descriptor instead.
func (*KVSetRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *KVSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KVSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type KVSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSetResponse) Reset() {
	*x = KVSetResponse{}
	mi := &file_contract_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetResponse) ProtoMessage() {}

func (x *KVSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetResponse.ProtoReflect.Descriptor instead.
func (*KVSetResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{17}
}

type KVDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDelRequest) Reset() {
	*x = KVDelRequest{}
	mi := &file_contract_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDelRequest) ProtoMessage() {}

func (x *KVDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDelRequest.ProtoReflect.Descriptor instead.
func (*KVDelRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *KVDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDelResponse) Reset() {
	*x = KVDelResponse{}
	mi := &file_contract_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDelResponse) ProtoMessage() {}

func (x *KVDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDelResponse.ProtoReflect.Descriptor instead.
func (*KVDelResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{19}
}

type KVIncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVIncrRequest) Reset() {
	*x = KVIncrRequest{}
	mi := &file_contract_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVIncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVIncrRequest) ProtoMessage() {}

func (x *KVIncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVIncrRequest.ProtoReflect.Descriptor instead.
func (*KVIncrRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *KVIncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVIncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVIncrResponse) Reset() {
	*x = KVIncrResponse{}
	mi := &file_contract_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVIncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVIncrResponse) ProtoMessage() {}

func (x *KVIncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVIncrResponse.ProtoReflect.Descriptor instead.
func (*KVIncrResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *KVIncrResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EmitEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_contract_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *EmitEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmitEventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type EmitEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventResponse) Reset() {
	*x = EmitEventResponse{}
	mi := &file_contract_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventResponse) ProtoMessage() {}

func (x *EmitEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventResponse.ProtoReflect.Descriptor instead.
func (*EmitEventResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{23}
}

var File_contract_plugin_proto protoreflect.FileDescriptor

const file_contract_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15contract/plugin.proto\x12\x0fnilda.plugin.v2\"\xc3\x03\n" +
	"\vInitRequest\x12\x1d\n" +
	"\n" +
	"plugin_key\x18\x01 \x01(\tR\tpluginKey\x12#\n" +
	"\rnilda_version\x18\x02 \x01(\tR\fnildaVersion\x121\n" +
	"\x14granted_capabilities\x18\x03 \x03(\tR\x13grantedCapabilities\x12#\n" +
	"\rdatastore_dsn\x18\x04 \x01(\tR\fdatastoreDsn\x12!\n" +
	"\fkv_namespace\x18\x05 \x01(\tR\vkvNamespace\x12$\n" +
	"\x0ehost_broker_id\x18\x06 \x01(\rR\fhostBrokerId\x12 \n" +
	"\fapi_base_url\x18\a \x01(\tR\n" +
	"apiBaseUrl\x12\x1b\n" +
	"\tapi_token\x18\b \x01(\tR\bapiToken\x12\x1d\n" +
	"\n" +
	"api_scopes\x18\t \x03(\tR\tapiScopes\x12#\n" +
	"\rsettings_json\x18\n" +
	" \x01(\fR\fsettingsJson\x12)\n" +
	"\x10previous_version\x18\v \x01(\tR\x0fpreviousVersion\x12!\n" +
	"\froute_prefix\x18\f \x01(\tR\vroutePrefix\"\xcc\x01\n" +
	"\fInitResponse\x12\x1d\n" +
	"\n" +
	"route_addr\x18\x01 \x01(\tR\trouteAddr\x12\x14\n" +
	"\x05hooks\x18\x02 \x03(\tR\x05hooks\x12\x16\n" +
	"\x06events\x18\x03 \x03(\tR\x06events\x127\n" +
	"\tschedules\x18\x04 \x03(\v2\x19.nilda.plugin.v2.ScheduleR\tschedules\x126\n" +
	"\tabilities\x18\x05 \x03(\v2\x18.nilda.plugin.v2.AbilityR\tabilities\"\xab\x01\n" +
	"\aAbility\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05class\x18\x04 \x01(\tR\x05class\x12!\n" +
	"\finput_schema\x18\x05 \x01(\tR\vinputSchema\x12\x1b\n" +
	"\tread_only\x18\x06 \x01(\bR\breadOnly\"2\n" +
	"\bSchedule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cron\x18\x02 \x01(\tR\x04cron\";\n" +
	"\vHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\fHookResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"?\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x0f\n" +
	"\rEventResponse\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"e\n" +
	"\x15RevokeIdentityRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"?\n" +
	"\x16RevokeIdentityResponse\x12%\n" +
	"\x0esessions_ended\x18\x01 \x01(\x05R\rsessionsEnded\"d\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\"\x13\n" +
	"\x11SendEmailResponse\" \n" +
	"\fKVGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\rKVGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"W\n" +
	"\fKVSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x0f\n" +
	"\rKVSetResponse\" \n" +
	"\fKVDelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x0f\n" +
	"\rKVDelResponse\"!\n" +
	"\rKVIncrRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x0eKVIncrResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"C\n" +
	"\x10EmitEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x13\n" +
	"\x11EmitEventResponse2\xb8\x02\n" +
	"\rPluginService\x12C\n" +
	"\x04Init\x12\x1c.nilda.plugin.v2.InitRequest\x1a\x1d.nilda.plugin.v2.InitResponse\x12I\n" +
	"\n" +
	"HandleHook\x12\x1c.nilda.plugin.v2.HookRequest\x1a\x1d.nilda.plugin.v2.HookResponse\x12L\n" +
	"\vHandleEvent\x12\x1d.nilda.plugin.v2.EventRequest\x1a\x1e.nilda.plugin.v2.EventResponse\x12I\n" +
	"\x06Health\x12\x1e.nilda.plugin.v2.HealthRequest\x1a\x1f.nilda.plugin.v2.HealthResponse2\xbb\x04\n" +
	"\vHostService\x12F\n" +
	"\x05KVGet\x12\x1d.nilda.plugin.v2.KVGetRequest\x1a\x1e.nilda.plugin.v2.KVGetResponse\x12F\n" +
	"\x05KVSet\x12\x1d.nilda.plugin.v2.KVSetRequest\x1a\x1e.nilda.plugin.v2.KVSetResponse\x12F\n" +
	"\x05KVDel\x12\x1d.nilda.plugin.v2.KVDelRequest\x1a\x1e.nilda.plugin.v2.KVDelResponse\x12I\n" +
	"\x06KVIncr\x12\x1e.nilda.plugin.v2.KVIncrRequest\x1a\x1f.nilda.plugin.v2.KVIncrResponse\x12R\n" +
	"\tEmitEvent\x12!.nilda.plugin.v2.EmitEventRequest\x1a\".nilda.plugin.v2.EmitEventResponse\x12R\n" +
	"\tSendEmail\x12!.nilda.plugin.v2.SendEmailRequest\x1a\".nilda.plugin.v2.SendEmailResponse\x12a\n" +
	"\x0eRevokeIdentity\x12&.nilda.plugin.v2.RevokeIdentityRequest\x1a'.nilda.plugin.v2.RevokeIdentityResponseB4Z2gitlab.com/nildalabs/nilda-sdk/plugin-sdk/contractb\x06proto3"

var (
	file_contract_plugin_proto_rawDescOnce sync.Once
	file_contract_plugin_proto_rawDescData []byte
)

func file_contract_plugin_proto_rawDescGZIP() []byte {
	file_contract_plugin_proto_rawDescOnce.Do(func() {
		file_contract_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_plugin_proto_rawDesc), len(file_contract_plugin_proto_rawDesc)))
	})
	return file_contract_plugin_proto_rawDescData
}

var file_contract_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_contract_plugin_proto_goTypes = []any{
	(*InitRequest)(nil),            // 0: nilda.plugin.v2.InitRequest
	(*InitResponse)(nil),           // 1: nilda.plugin.v2.InitResponse
	(*Ability)(nil),                // 2: nilda.plugin.v2.Ability
	(*Schedule)(nil),               // 3: nilda.plugin.v2.Schedule
	(*HookRequest)(nil),            // 4: nilda.plugin.v2.HookRequest
	(*HookResponse)(nil),           // 5: nilda.plugin.v2.HookResponse
	(*EventRequest)(nil),           // 6: nilda.plugin.v2.EventRequest
	(*EventResponse)(nil),          // 7: nilda.plugin.v2.EventResponse
	(*HealthRequest)(nil),          // 8: nilda.plugin.v2.HealthRequest
	(*HealthResponse)(nil),         // 9: nilda.plugin.v2.HealthResponse
	(*RevokeIdentityRequest)(nil),  // 10: nilda.plugin.v2.RevokeIdentityRequest
	(*RevokeIdentityResponse)(nil), // 11: nilda.plugin.v2.RevokeIdentityResponse
	(*SendEmailRequest)(nil),       // 12: nilda.plugin.v2.SendEmailRequest
	(*SendEmailResponse)(nil),      // 13: nilda.plugin.v2.SendEmailResponse
	(*KVGetRequest)(nil),           // 14: nilda.plugin.v2.KVGetRequest
	(*KVGetResponse)(nil),          // 15: nilda.plugin.v2.KVGetResponse
	(*KVSetRequest)(nil),           // 16: nilda.plugin.v2.KVSetRequest
	(*KVSetResponse)(nil),          // 17: nilda.plugin.v2.KVSetResponse
	(*KVDelRequest)(nil),           // 18: nilda.plugin.v2.KVDelRequest
	(*KVDelResponse)(nil),          // 19: nilda.plugin.v2.KVDelResponse
	(*KVIncrRequest)(nil),          // 20: nilda.plugin.v2.KVIncrRequest
	(*KVIncrResponse)(nil),         // 21: nilda.plugin.v2.KVIncrResponse
	(*EmitEventRequest)(nil),       // 22: nilda.plugin.v2.EmitEventRequest
	(*EmitEventResponse)(nil),      // 23: nilda.plugin.v2.EmitEventResponse
}
var file_contract_plugin_proto_depIdxs = []int32{
	3,  // 0: nilda.plugin.v2.InitResponse.schedules:type_name -> nilda.plugin.v2.Schedule
	2,  // 1: nilda.plugin.v2.InitResponse.abilities:type_name -> nilda.plugin.v2.Ability
	0,  // 2: nilda.plugin.v2.PluginService.Init:input_type -> nilda.plugin.v2.InitRequest
	4,  // 3: nilda.plugin.v2.PluginService.HandleHook:input_type -> nilda.plugin.v2.HookRequest
	6,  // 4: nilda.plugin.v2.PluginService.HandleEvent:input_type -> nilda.plugin.v2.EventRequest
	8,  // 5: nilda.plugin.v2.PluginService.Health:input_type -> nilda.plugin.v2.HealthRequest
	14, // 6: nilda.plugin.v2.HostService.KVGet:input_type -> nilda.plugin.v2.KVGetRequest
	16, // 7: nilda.plugin.v2.HostService.KVSet:input_type -> nilda.plugin.v2.KVSetRequest
	18, // 8: nilda.plugin.v2.HostService.KVDel:input_type -> nilda.plugin.v2.KVDelRequest
	20, // 9: nilda.plugin.v2.HostService.KVIncr:input_type -> nilda.plugin.v2.KVIncrRequest
	22, // 10: nilda.plugin.v2.HostService.EmitEvent:input_type -> nilda.plugin.v2.EmitEventRequest
	12, // 11: nilda.plugin.v2.HostService.SendEmail:input_type -> nilda.plugin.v2.SendEmailRequest
	10, // 12: nilda.plugin.v2.HostService.RevokeIdentity:input_type -> nilda.plugin.v2.RevokeIdentityRequest
	1,  // 13: nilda.plugin.v2.PluginService.Init:output_type -> nilda.plugin.v2.InitResponse
	5,  // 14: nilda.plugin.v2.PluginService.HandleHook:output_type -> nilda.plugin.v2.HookResponse
	7,  // 15: nilda.plugin.v2.PluginService.HandleEvent:output_type -> nilda.plugin.v2.EventResponse
	9,  // 16: nilda.plugin.v2.PluginService.Health:output_type -> nilda.plugin.v2.HealthResponse
	15, // 17: nilda.plugin.v2.HostService.KVGet:output_type -> nilda.plugin.v2.KVGetResponse
	17, // 18: nilda.plugin.v2.HostService.KVSet:output_type -> nilda.plugin.v2.KVSetResponse
	19, // 19: nilda.plugin.v2.HostService.KVDel:output_type -> nilda.plugin.v2.KVDelResponse
	21, // 20: nilda.plugin.v2.HostService.KVIncr:output_type -> nilda.plugin.v2.KVIncrResponse
	23, // 21: nilda.plugin.v2.HostService.EmitEvent:output_type -> nilda.plugin.v2.EmitEventResponse
	13, // 22: nilda.plugin.v2.HostService.SendEmail:output_type -> nilda.plugin.v2.SendEmailResponse
	11, // 23: nilda.plugin.v2.HostService.RevokeIdentity:output_type -> nilda.plugin.v2.RevokeIdentityResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_contract_plugin_proto_init() }
func file_contract_plugin_proto_init() {
	if File_contract_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_plugin_proto_rawDesc), len(file_contract_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_contract_plugin_proto_goTypes,
		DependencyIndexes: file_contract_plugin_proto_depIdxs,
		MessageInfos:      file_contract_plugin_proto_msgTypes,
	}.Build()
	File_contract_plugin_proto = out.File
	file_contract_plugin_proto_goTypes = nil
	file_contract_plugin_proto_depIdxs = nil
}
