// Nilda plugin contract v2 (SPEC_98). The single source of truth for the Core<->plugin gRPC wire.
//
// Versioning: this contract is carried by plugin-sdk (semver) and guarded by the go-plugin handshake
// ProtocolVersion (Terraform-style) — an incompatible plugin is rejected at load, never silently
// broken. Within a version, fields are only ever ADDED (proto3 forward compatibility); a breaking
// change ships a new package, which is what v2 is.
//
// WHAT CHANGED IN v2, and why it is worth a breaking change: v1's HostService carried five read
// methods and no way to write anything, so a plugin could read a page by slug and list a content type
// and nothing else. No shop could create a product, no importer could create a post — not because
// out-of-process plugins are limited, but because that hand-picked subset was all anything had wired.
// Meanwhile Core has a complete API. v2 removes the subset and hands the plugin a scoped token onto
// that API instead.
//
// The resulting rule is worth stating plainly, because it is the shape of the whole system:
//
//     gRPC is how Core calls the plugin.  HTTP is how the plugin calls Core.
//
// Direction 1 — PluginService (Core -> plugin): lifecycle + hook/event dispatch. Every call is made
// with the per-call timeout (PLUGIN_CALL_TIMEOUT); a slow plugin fails the CALL, never Core.
// Direction 2 — HostService (plugin -> Core, over the go-plugin GRPCBroker): what genuinely belongs on
// this transport — the plugin's own KV namespace and event emission. Capability-enforced server-side
// (deny-by-default); the broker connection belongs to exactly one plugin, so its identity is ambient
// and unforgeable. Data access is not here; it is the API token in InitRequest.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: contract/plugin.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Init_FullMethodName        = "/nilda.plugin.v2.PluginService/Init"
	PluginService_HandleHook_FullMethodName  = "/nilda.plugin.v2.PluginService/HandleHook"
	PluginService_HandleEvent_FullMethodName = "/nilda.plugin.v2.PluginService/HandleEvent"
	PluginService_Health_FullMethodName      = "/nilda.plugin.v2.PluginService/Health"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// Init hands the plugin its runtime context exactly once after the handshake: the granted
	// capabilities, its scoped datastore DSN (empty unless granted+provisioned), and the broker
	// stream id where Core serves HostService. The plugin answers with what it wants wired:
	// hook names, event subscriptions, and (route plugins) its resident HTTP address.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// HandleHook dispatches one hook invocation. Filter-style: the (possibly modified) payload is
	// returned; a plugin that doesn't modify echoes the payload back.
	HandleHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error)
	// HandleEvent delivers one event (best-effort, timeout-bounded; delivery guarantees are a
	// documented SPEC_98 bound — at-least-once/replay is a later SPEC).
	HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	// Health is defined and never called: Nilda supervises a plugin by its process exiting and by its calls
	// failing, not by a probe. Answer it anyway — a later Core may ask.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, PluginService_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleHook(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) HandleEvent(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, PluginService_HandleEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
type PluginServiceServer interface {
	// Init hands the plugin its runtime context exactly once after the handshake: the granted
	// capabilities, its scoped datastore DSN (empty unless granted+provisioned), and the broker
	// stream id where Core serves HostService. The plugin answers with what it wants wired:
	// hook names, event subscriptions, and (route plugins) its resident HTTP address.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// HandleHook dispatches one hook invocation. Filter-style: the (possibly modified) payload is
	// returned; a plugin that doesn't modify echoes the payload back.
	HandleHook(context.Context, *HookRequest) (*HookResponse, error)
	// HandleEvent delivers one event (best-effort, timeout-bounded; delivery guarantees are a
	// documented SPEC_98 bound — at-least-once/replay is a later SPEC).
	HandleEvent(context.Context, *EventRequest) (*EventResponse, error)
	// Health is defined and never called: Nilda supervises a plugin by its process exiting and by its calls
	// failing, not by a probe. Answer it anyway — a later Core may ask.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginServiceServer) HandleHook(context.Context, *HookRequest) (*HookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleHook not implemented")
}
func (UnimplementedPluginServiceServer) HandleEvent(context.Context, *EventRequest) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleEvent not implemented")
}
func (UnimplementedPluginServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call pancis, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleHook(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_HandleEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).HandleEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_HandleEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).HandleEvent(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nilda.plugin.v2.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _PluginService_Init_Handler,
		},
		{
			MethodName: "HandleHook",
			Handler:    _PluginService_HandleHook_Handler,
		},
		{
			MethodName: "HandleEvent",
			Handler:    _PluginService_HandleEvent_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PluginService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/plugin.proto",
}

const (
	HostService_KVGet_FullMethodName          = "/nilda.plugin.v2.HostService/KVGet"
	HostService_KVSet_FullMethodName          = "/nilda.plugin.v2.HostService/KVSet"
	HostService_KVDel_FullMethodName          = "/nilda.plugin.v2.HostService/KVDel"
	HostService_KVIncr_FullMethodName         = "/nilda.plugin.v2.HostService/KVIncr"
	HostService_EmitEvent_FullMethodName      = "/nilda.plugin.v2.HostService/EmitEvent"
	HostService_SendEmail_FullMethodName      = "/nilda.plugin.v2.HostService/SendEmail"
	HostService_RevokeIdentity_FullMethodName = "/nilda.plugin.v2.HostService/RevokeIdentity"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostServiceClient interface {
	// kv — the plugin's scoped Dragonfly namespace.
	KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error)
	KVSet(ctx context.Context, in *KVSetRequest, opts ...grpc.CallOption) (*KVSetResponse, error)
	KVDel(ctx context.Context, in *KVDelRequest, opts ...grpc.CallOption) (*KVDelResponse, error)
	KVIncr(ctx context.Context, in *KVIncrRequest, opts ...grpc.CallOption) (*KVIncrResponse, error)
	// events — emit a plugin-originated event into Core's pipeline.
	EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error)
	// email — send mail through Core's mailer (requires `email`). Core fixes the sender identity, so a
	// plugin can never forge the site's address; a booking plugin sends its own confirmations without
	// needing SMTP credentials of its own, and without the owner configuring mail twice.
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	// auth — end every session of somebody an identity provider has deprovisioned (requires
	// `auth_provider`).
	//
	// THE ONE ASYMMETRY WORTH STATING OUTRIGHT: a plugin may never create authority, and may destroy it.
	//
	// Nothing on this service lets a plugin sign anybody in — that is the whole shape of `auth_provider`,
	// where the plugin returns an assertion and Core decides. This method is the mirror image, and it is
	// safe for exactly that reason: the worst a hostile plugin achieves with it is signing people out.
	//
	// It is also what makes SSO mean what it claims. "Someone leaves the company and their access here ends
	// in the same second" cannot be delivered by anything that only runs at sign-in; it needs the directory
	// to be able to reach in. The provider's back-channel logout token arrives on the plugin's own route,
	// the plugin validates it, and this is how it tells Core.
	//
	// Core enforces ownership: `provider` is your LOCAL key, and a plugin can only ever revoke identities
	// recorded under a provider it owns.
	RevokeIdentity(ctx context.Context, in *RevokeIdentityRequest, opts ...grpc.CallOption) (*RevokeIdentityResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) KVGet(ctx context.Context, in *KVGetRequest, opts ...grpc.CallOption) (*KVGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVGetResponse)
	err := c.cc.Invoke(ctx, HostService_KVGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVSet(ctx context.Context, in *KVSetRequest, opts ...grpc.CallOption) (*KVSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVSetResponse)
	err := c.cc.Invoke(ctx, HostService_KVSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVDel(ctx context.Context, in *KVDelRequest, opts ...grpc.CallOption) (*KVDelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVDelResponse)
	err := c.cc.Invoke(ctx, HostService_KVDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) KVIncr(ctx context.Context, in *KVIncrRequest, opts ...grpc.CallOption) (*KVIncrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KVIncrResponse)
	err := c.cc.Invoke(ctx, HostService_KVIncr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) EmitEvent(ctx context.Context, in *EmitEventRequest, opts ...grpc.CallOption) (*EmitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitEventResponse)
	err := c.cc.Invoke(ctx, HostService_EmitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, HostService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) RevokeIdentity(ctx context.Context, in *RevokeIdentityRequest, opts ...grpc.CallOption) (*RevokeIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeIdentityResponse)
	err := c.cc.Invoke(ctx, HostService_RevokeIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
type HostServiceServer interface {
	// kv — the plugin's scoped Dragonfly namespace.
	KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error)
	KVSet(context.Context, *KVSetRequest) (*KVSetResponse, error)
	KVDel(context.Context, *KVDelRequest) (*KVDelResponse, error)
	KVIncr(context.Context, *KVIncrRequest) (*KVIncrResponse, error)
	// events — emit a plugin-originated event into Core's pipeline.
	EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error)
	// email — send mail through Core's mailer (requires `email`). Core fixes the sender identity, so a
	// plugin can never forge the site's address; a booking plugin sends its own confirmations without
	// needing SMTP credentials of its own, and without the owner configuring mail twice.
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	// auth — end every session of somebody an identity provider has deprovisioned (requires
	// `auth_provider`).
	//
	// THE ONE ASYMMETRY WORTH STATING OUTRIGHT: a plugin may never create authority, and may destroy it.
	//
	// Nothing on this service lets a plugin sign anybody in — that is the whole shape of `auth_provider`,
	// where the plugin returns an assertion and Core decides. This method is the mirror image, and it is
	// safe for exactly that reason: the worst a hostile plugin achieves with it is signing people out.
	//
	// It is also what makes SSO mean what it claims. "Someone leaves the company and their access here ends
	// in the same second" cannot be delivered by anything that only runs at sign-in; it needs the directory
	// to be able to reach in. The provider's back-channel logout token arrives on the plugin's own route,
	// the plugin validates it, and this is how it tells Core.
	//
	// Core enforces ownership: `provider` is your LOCAL key, and a plugin can only ever revoke identities
	// recorded under a provider it owns.
	RevokeIdentity(context.Context, *RevokeIdentityRequest) (*RevokeIdentityResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) KVGet(context.Context, *KVGetRequest) (*KVGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVGet not implemented")
}
func (UnimplementedHostServiceServer) KVSet(context.Context, *KVSetRequest) (*KVSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVSet not implemented")
}
func (UnimplementedHostServiceServer) KVDel(context.Context, *KVDelRequest) (*KVDelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVDel not implemented")
}
func (UnimplementedHostServiceServer) KVIncr(context.Context, *KVIncrRequest) (*KVIncrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KVIncr not implemented")
}
func (UnimplementedHostServiceServer) EmitEvent(context.Context, *EmitEventRequest) (*EmitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmitEvent not implemented")
}
func (UnimplementedHostServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedHostServiceServer) RevokeIdentity(context.Context, *RevokeIdentityRequest) (*RevokeIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeIdentity not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call pancis, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_KVGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVGet(ctx, req.(*KVGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVSet(ctx, req.(*KVSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVDelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVDel(ctx, req.(*KVDelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_KVIncr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVIncrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).KVIncr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_KVIncr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).KVIncr(ctx, req.(*KVIncrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_EmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).EmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_EmitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).EmitEvent(ctx, req.(*EmitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_RevokeIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RevokeIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RevokeIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RevokeIdentity(ctx, req.(*RevokeIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nilda.plugin.v2.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KVGet",
			Handler:    _HostService_KVGet_Handler,
		},
		{
			MethodName: "KVSet",
			Handler:    _HostService_KVSet_Handler,
		},
		{
			MethodName: "KVDel",
			Handler:    _HostService_KVDel_Handler,
		},
		{
			MethodName: "KVIncr",
			Handler:    _HostService_KVIncr_Handler,
		},
		{
			MethodName: "EmitEvent",
			Handler:    _HostService_EmitEvent_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _HostService_SendEmail_Handler,
		},
		{
			MethodName: "RevokeIdentity",
			Handler:    _HostService_RevokeIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/plugin.proto",
}
