// Nilda plugin contract v1 (SPEC_98). The single source of truth for the Core<->plugin gRPC wire.
//
// Versioning: this contract is carried by plugin-sdk (semver) and guarded by the go-plugin handshake
// ProtocolVersion (Terraform-style) — an incompatible plugin is rejected at load, never silently
// broken. Within v1, fields are only ever ADDED (proto3 forward compatibility); a breaking change
// ships nilda.plugin.v2.
//
// Direction 1 — PluginService (Core -> plugin): lifecycle + hook/event dispatch. Every call is made
// with the per-call timeout (PLUGIN_CALL_TIMEOUT); a slow plugin fails the CALL, never Core.
// Direction 2 — HostService (plugin -> Core, served over the go-plugin GRPCBroker): the ONLY door a
// plugin has into Core. Every method is capability-enforced server-side (deny-by-default) — the
// broker connection belongs to exactly one plugin, so the plugin identity is ambient and unforgeable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: contract/plugin.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PluginKey           string                 `protobuf:"bytes,1,opt,name=plugin_key,json=pluginKey,proto3" json:"plugin_key,omitempty"`                               // the manifest key (also schema/KV slug)
	NildaVersion        string                 `protobuf:"bytes,2,opt,name=nilda_version,json=nildaVersion,proto3" json:"nilda_version,omitempty"`                      // the running Core version
	GrantedCapabilities []string               `protobuf:"bytes,3,rep,name=granted_capabilities,json=grantedCapabilities,proto3" json:"granted_capabilities,omitempty"` // deny-by-default: only these are callable
	DatastoreDsn        string                 `protobuf:"bytes,4,opt,name=datastore_dsn,json=datastoreDsn,proto3" json:"datastore_dsn,omitempty"`                      // scoped least-privilege DSN; empty unless `datastore`
	KvNamespace         string                 `protobuf:"bytes,5,opt,name=kv_namespace,json=kvNamespace,proto3" json:"kv_namespace,omitempty"`                         // informational (KV ops go through HostService)
	HostBrokerId        uint32                 `protobuf:"varint,6,opt,name=host_broker_id,json=hostBrokerId,proto3" json:"host_broker_id,omitempty"`                   // GRPCBroker stream id serving HostService
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_contract_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *InitRequest) GetPluginKey() string {
	if x != nil {
		return x.PluginKey
	}
	return ""
}

func (x *InitRequest) GetNildaVersion() string {
	if x != nil {
		return x.NildaVersion
	}
	return ""
}

func (x *InitRequest) GetGrantedCapabilities() []string {
	if x != nil {
		return x.GrantedCapabilities
	}
	return nil
}

func (x *InitRequest) GetDatastoreDsn() string {
	if x != nil {
		return x.DatastoreDsn
	}
	return ""
}

func (x *InitRequest) GetKvNamespace() string {
	if x != nil {
		return x.KvNamespace
	}
	return ""
}

func (x *InitRequest) GetHostBrokerId() uint32 {
	if x != nil {
		return x.HostBrokerId
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteAddr     string                 `protobuf:"bytes,1,opt,name=route_addr,json=routeAddr,proto3" json:"route_addr,omitempty"` // "host:port" of the plugin's resident HTTP server; empty unless `route`
	Hooks         []string               `protobuf:"bytes,2,rep,name=hooks,proto3" json:"hooks,omitempty"`                          // hook names to receive (requires `hooks` capability)
	Events        []string               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`                        // event types to receive (requires `events` capability)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_contract_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitResponse) GetRouteAddr() string {
	if x != nil {
		return x.RouteAddr
	}
	return ""
}

func (x *InitResponse) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *InitResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_contract_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // JSON, possibly modified (filter hooks)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_contract_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_contract_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *EventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type EventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_contract_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{5}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_contract_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_contract_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteRequest) Reset() {
	*x = SiteRequest{}
	mi := &file_contract_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteRequest) ProtoMessage() {}

func (x *SiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteRequest.ProtoReflect.Descriptor instead.
func (*SiteRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{8}
}

type Site struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,3,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Locale        string                 `protobuf:"bytes,4,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Site) Reset() {
	*x = Site{}
	mi := &file_contract_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Site) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Site) ProtoMessage() {}

func (x *Site) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Site.ProtoReflect.Descriptor instead.
func (*Site) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Site) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Site) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Site) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Site) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type PageBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageBySlugRequest) Reset() {
	*x = PageBySlugRequest{}
	mi := &file_contract_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageBySlugRequest) ProtoMessage() {}

func (x *PageBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageBySlugRequest.ProtoReflect.Descriptor instead.
func (*PageBySlugRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *PageBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type PageBySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *Page                  `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageBySlugResponse) Reset() {
	*x = PageBySlugResponse{}
	mi := &file_contract_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageBySlugResponse) ProtoMessage() {}

func (x *PageBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageBySlugResponse.ProtoReflect.Descriptor instead.
func (*PageBySlugResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *PageBySlugResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *PageBySlugResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type Page struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug            string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Excerpt         string                 `protobuf:"bytes,5,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	BodyJson        []byte                 `protobuf:"bytes,6,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	PublishedAtUnix int64                  `protobuf:"varint,7,opt,name=published_at_unix,json=publishedAtUnix,proto3" json:"published_at_unix,omitempty"`
	AuthorId        string                 `protobuf:"bytes,8,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	ValuesJson      []byte                 `protobuf:"bytes,9,opt,name=values_json,json=valuesJson,proto3" json:"values_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_contract_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *Page) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Page) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Page) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Page) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Page) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *Page) GetBodyJson() []byte {
	if x != nil {
		return x.BodyJson
	}
	return nil
}

func (x *Page) GetPublishedAtUnix() int64 {
	if x != nil {
		return x.PublishedAtUnix
	}
	return 0
}

func (x *Page) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Page) GetValuesJson() []byte {
	if x != nil {
		return x.ValuesJson
	}
	return nil
}

type ContentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeKey       string                 `protobuf:"bytes,1,opt,name=type_key,json=typeKey,proto3" json:"type_key,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 1-based; Core clamps
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // Core clamps (default 20, max 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentListRequest) Reset() {
	*x = ContentListRequest{}
	mi := &file_contract_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentListRequest) ProtoMessage() {}

func (x *ContentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentListRequest.ProtoReflect.Descriptor instead.
func (*ContentListRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ContentListRequest) GetTypeKey() string {
	if x != nil {
		return x.TypeKey
	}
	return ""
}

func (x *ContentListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContentListRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Slug            string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Excerpt         string                 `protobuf:"bytes,5,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	PublishedAtUnix int64                  `protobuf:"varint,6,opt,name=published_at_unix,json=publishedAtUnix,proto3" json:"published_at_unix,omitempty"`
	AuthorId        string                 `protobuf:"bytes,7,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	mi := &file_contract_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ListItem) GetExcerpt() string {
	if x != nil {
		return x.Excerpt
	}
	return ""
}

func (x *ListItem) GetPublishedAtUnix() int64 {
	if x != nil {
		return x.PublishedAtUnix
	}
	return 0
}

func (x *ListItem) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type ContentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ListItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentListResponse) Reset() {
	*x = ContentListResponse{}
	mi := &file_contract_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentListResponse) ProtoMessage() {}

func (x *ContentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentListResponse.ProtoReflect.Descriptor instead.
func (*ContentListResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ContentListResponse) GetItems() []*ListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ContentListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ContentListResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ContentListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserByIDRequest) Reset() {
	*x = UserByIDRequest{}
	mi := &file_contract_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserByIDRequest) ProtoMessage() {}

func (x *UserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserByIDRequest.ProtoReflect.Descriptor instead.
func (*UserByIDRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *UserByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_contract_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type MediaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaByIDRequest) Reset() {
	*x = MediaByIDRequest{}
	mi := &file_contract_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaByIDRequest) ProtoMessage() {}

func (x *MediaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaByIDRequest.ProtoReflect.Descriptor instead.
func (*MediaByIDRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *MediaByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Mime          string                 `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_contract_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type KVGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetRequest) Reset() {
	*x = KVGetRequest{}
	mi := &file_contract_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRequest) ProtoMessage() {}

func (x *KVGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRequest.ProtoReflect.Descriptor instead.
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *KVGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetResponse) Reset() {
	*x = KVGetResponse{}
	mi := &file_contract_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetResponse) ProtoMessage() {}

func (x *KVGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetResponse.ProtoReflect.Descriptor instead.
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *KVGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KVGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type KVSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = no expiry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSetRequest) Reset() {
	*x = KVSetRequest{}
	mi := &file_contract_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetRequest) ProtoMessage() {}

func (x *KVSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetRequest.ProtoReflect.Descriptor instead.
func (*KVSetRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *KVSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KVSetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type KVSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSetResponse) Reset() {
	*x = KVSetResponse{}
	mi := &file_contract_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSetResponse) ProtoMessage() {}

func (x *KVSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSetResponse.ProtoReflect.Descriptor instead.
func (*KVSetResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{23}
}

type KVDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDelRequest) Reset() {
	*x = KVDelRequest{}
	mi := &file_contract_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDelRequest) ProtoMessage() {}

func (x *KVDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDelRequest.ProtoReflect.Descriptor instead.
func (*KVDelRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *KVDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDelResponse) Reset() {
	*x = KVDelResponse{}
	mi := &file_contract_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDelResponse) ProtoMessage() {}

func (x *KVDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDelResponse.ProtoReflect.Descriptor instead.
func (*KVDelResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{25}
}

type KVIncrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVIncrRequest) Reset() {
	*x = KVIncrRequest{}
	mi := &file_contract_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVIncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVIncrRequest) ProtoMessage() {}

func (x *KVIncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVIncrRequest.ProtoReflect.Descriptor instead.
func (*KVIncrRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *KVIncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVIncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVIncrResponse) Reset() {
	*x = KVIncrResponse{}
	mi := &file_contract_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVIncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVIncrResponse) ProtoMessage() {}

func (x *KVIncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVIncrResponse.ProtoReflect.Descriptor instead.
func (*KVIncrResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *KVIncrResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EmitEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	DataJson      []byte                 `protobuf:"bytes,2,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventRequest) Reset() {
	*x = EmitEventRequest{}
	mi := &file_contract_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventRequest) ProtoMessage() {}

func (x *EmitEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventRequest.ProtoReflect.Descriptor instead.
func (*EmitEventRequest) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *EmitEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmitEventRequest) GetDataJson() []byte {
	if x != nil {
		return x.DataJson
	}
	return nil
}

type EmitEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitEventResponse) Reset() {
	*x = EmitEventResponse{}
	mi := &file_contract_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitEventResponse) ProtoMessage() {}

func (x *EmitEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitEventResponse.ProtoReflect.Descriptor instead.
func (*EmitEventResponse) Descriptor() ([]byte, []int) {
	return file_contract_plugin_proto_rawDescGZIP(), []int{29}
}

var File_contract_plugin_proto protoreflect.FileDescriptor

const file_contract_plugin_proto_rawDesc = "" +
	"\n" +
	"\x15contract/plugin.proto\x12\x0fnilda.plugin.v1\"\xf2\x01\n" +
	"\vInitRequest\x12\x1d\n" +
	"\n" +
	"plugin_key\x18\x01 \x01(\tR\tpluginKey\x12#\n" +
	"\rnilda_version\x18\x02 \x01(\tR\fnildaVersion\x121\n" +
	"\x14granted_capabilities\x18\x03 \x03(\tR\x13grantedCapabilities\x12#\n" +
	"\rdatastore_dsn\x18\x04 \x01(\tR\fdatastoreDsn\x12!\n" +
	"\fkv_namespace\x18\x05 \x01(\tR\vkvNamespace\x12$\n" +
	"\x0ehost_broker_id\x18\x06 \x01(\rR\fhostBrokerId\"[\n" +
	"\fInitResponse\x12\x1d\n" +
	"\n" +
	"route_addr\x18\x01 \x01(\tR\trouteAddr\x12\x14\n" +
	"\x05hooks\x18\x02 \x03(\tR\x05hooks\x12\x16\n" +
	"\x06events\x18\x03 \x03(\tR\x06events\";\n" +
	"\vHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"(\n" +
	"\fHookResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"?\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x0f\n" +
	"\rEventResponse\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\r\n" +
	"\vSiteRequest\"q\n" +
	"\x04Site\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bbase_url\x18\x03 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06locale\x18\x04 \x01(\tR\x06locale\"'\n" +
	"\x11PageBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"U\n" +
	"\x12PageBySlugResponse\x12)\n" +
	"\x04page\x18\x01 \x01(\v2\x15.nilda.plugin.v1.PageR\x04page\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xf5\x01\n" +
	"\x04Page\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\aexcerpt\x18\x05 \x01(\tR\aexcerpt\x12\x1b\n" +
	"\tbody_json\x18\x06 \x01(\fR\bbodyJson\x12*\n" +
	"\x11published_at_unix\x18\a \x01(\x03R\x0fpublishedAtUnix\x12\x1b\n" +
	"\tauthor_id\x18\b \x01(\tR\bauthorId\x12\x1f\n" +
	"\vvalues_json\x18\t \x01(\fR\n" +
	"valuesJson\"W\n" +
	"\x12ContentListRequest\x12\x19\n" +
	"\btype_key\x18\x01 \x01(\tR\atypeKey\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"\xbb\x01\n" +
	"\bListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x18\n" +
	"\aexcerpt\x18\x05 \x01(\tR\aexcerpt\x12*\n" +
	"\x11published_at_unix\x18\x06 \x01(\x03R\x0fpublishedAtUnix\x12\x1b\n" +
	"\tauthor_id\x18\a \x01(\tR\bauthorId\"\x84\x01\n" +
	"\x13ContentListResponse\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.nilda.plugin.v1.ListItemR\x05items\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"!\n" +
	"\x0fUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"\"\n" +
	"\x10MediaByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04mime\x18\x03 \x01(\tR\x04mime\" \n" +
	"\fKVGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\rKVGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"W\n" +
	"\fKVSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x0f\n" +
	"\rKVSetResponse\" \n" +
	"\fKVDelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x0f\n" +
	"\rKVDelResponse\"!\n" +
	"\rKVIncrRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"&\n" +
	"\x0eKVIncrResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"C\n" +
	"\x10EmitEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1b\n" +
	"\tdata_json\x18\x02 \x01(\fR\bdataJson\"\x13\n" +
	"\x11EmitEventResponse2\xb8\x02\n" +
	"\rPluginService\x12C\n" +
	"\x04Init\x12\x1c.nilda.plugin.v1.InitRequest\x1a\x1d.nilda.plugin.v1.InitResponse\x12I\n" +
	"\n" +
	"HandleHook\x12\x1c.nilda.plugin.v1.HookRequest\x1a\x1d.nilda.plugin.v1.HookResponse\x12L\n" +
	"\vHandleEvent\x12\x1d.nilda.plugin.v1.EventRequest\x1a\x1e.nilda.plugin.v1.EventResponse\x12I\n" +
	"\x06Health\x12\x1e.nilda.plugin.v1.HealthRequest\x1a\x1f.nilda.plugin.v1.HealthResponse2\x8d\x06\n" +
	"\vHostService\x12B\n" +
	"\vContentSite\x12\x1c.nilda.plugin.v1.SiteRequest\x1a\x15.nilda.plugin.v1.Site\x12\\\n" +
	"\x11ContentPageBySlug\x12\".nilda.plugin.v1.PageBySlugRequest\x1a#.nilda.plugin.v1.PageBySlugResponse\x12X\n" +
	"\vContentList\x12#.nilda.plugin.v1.ContentListRequest\x1a$.nilda.plugin.v1.ContentListResponse\x12C\n" +
	"\bUserByID\x12 .nilda.plugin.v1.UserByIDRequest\x1a\x15.nilda.plugin.v1.User\x12F\n" +
	"\tMediaByID\x12!.nilda.plugin.v1.MediaByIDRequest\x1a\x16.nilda.plugin.v1.Media\x12F\n" +
	"\x05KVGet\x12\x1d.nilda.plugin.v1.KVGetRequest\x1a\x1e.nilda.plugin.v1.KVGetResponse\x12F\n" +
	"\x05KVSet\x12\x1d.nilda.plugin.v1.KVSetRequest\x1a\x1e.nilda.plugin.v1.KVSetResponse\x12F\n" +
	"\x05KVDel\x12\x1d.nilda.plugin.v1.KVDelRequest\x1a\x1e.nilda.plugin.v1.KVDelResponse\x12I\n" +
	"\x06KVIncr\x12\x1e.nilda.plugin.v1.KVIncrRequest\x1a\x1f.nilda.plugin.v1.KVIncrResponse\x12R\n" +
	"\tEmitEvent\x12!.nilda.plugin.v1.EmitEventRequest\x1a\".nilda.plugin.v1.EmitEventResponseB*Z(gitlab.com/nilda-sdk/plugin-sdk/contractb\x06proto3"

var (
	file_contract_plugin_proto_rawDescOnce sync.Once
	file_contract_plugin_proto_rawDescData []byte
)

func file_contract_plugin_proto_rawDescGZIP() []byte {
	file_contract_plugin_proto_rawDescOnce.Do(func() {
		file_contract_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_plugin_proto_rawDesc), len(file_contract_plugin_proto_rawDesc)))
	})
	return file_contract_plugin_proto_rawDescData
}

var file_contract_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_contract_plugin_proto_goTypes = []any{
	(*InitRequest)(nil),         // 0: nilda.plugin.v1.InitRequest
	(*InitResponse)(nil),        // 1: nilda.plugin.v1.InitResponse
	(*HookRequest)(nil),         // 2: nilda.plugin.v1.HookRequest
	(*HookResponse)(nil),        // 3: nilda.plugin.v1.HookResponse
	(*EventRequest)(nil),        // 4: nilda.plugin.v1.EventRequest
	(*EventResponse)(nil),       // 5: nilda.plugin.v1.EventResponse
	(*HealthRequest)(nil),       // 6: nilda.plugin.v1.HealthRequest
	(*HealthResponse)(nil),      // 7: nilda.plugin.v1.HealthResponse
	(*SiteRequest)(nil),         // 8: nilda.plugin.v1.SiteRequest
	(*Site)(nil),                // 9: nilda.plugin.v1.Site
	(*PageBySlugRequest)(nil),   // 10: nilda.plugin.v1.PageBySlugRequest
	(*PageBySlugResponse)(nil),  // 11: nilda.plugin.v1.PageBySlugResponse
	(*Page)(nil),                // 12: nilda.plugin.v1.Page
	(*ContentListRequest)(nil),  // 13: nilda.plugin.v1.ContentListRequest
	(*ListItem)(nil),            // 14: nilda.plugin.v1.ListItem
	(*ContentListResponse)(nil), // 15: nilda.plugin.v1.ContentListResponse
	(*UserByIDRequest)(nil),     // 16: nilda.plugin.v1.UserByIDRequest
	(*User)(nil),                // 17: nilda.plugin.v1.User
	(*MediaByIDRequest)(nil),    // 18: nilda.plugin.v1.MediaByIDRequest
	(*Media)(nil),               // 19: nilda.plugin.v1.Media
	(*KVGetRequest)(nil),        // 20: nilda.plugin.v1.KVGetRequest
	(*KVGetResponse)(nil),       // 21: nilda.plugin.v1.KVGetResponse
	(*KVSetRequest)(nil),        // 22: nilda.plugin.v1.KVSetRequest
	(*KVSetResponse)(nil),       // 23: nilda.plugin.v1.KVSetResponse
	(*KVDelRequest)(nil),        // 24: nilda.plugin.v1.KVDelRequest
	(*KVDelResponse)(nil),       // 25: nilda.plugin.v1.KVDelResponse
	(*KVIncrRequest)(nil),       // 26: nilda.plugin.v1.KVIncrRequest
	(*KVIncrResponse)(nil),      // 27: nilda.plugin.v1.KVIncrResponse
	(*EmitEventRequest)(nil),    // 28: nilda.plugin.v1.EmitEventRequest
	(*EmitEventResponse)(nil),   // 29: nilda.plugin.v1.EmitEventResponse
}
var file_contract_plugin_proto_depIdxs = []int32{
	12, // 0: nilda.plugin.v1.PageBySlugResponse.page:type_name -> nilda.plugin.v1.Page
	14, // 1: nilda.plugin.v1.ContentListResponse.items:type_name -> nilda.plugin.v1.ListItem
	0,  // 2: nilda.plugin.v1.PluginService.Init:input_type -> nilda.plugin.v1.InitRequest
	2,  // 3: nilda.plugin.v1.PluginService.HandleHook:input_type -> nilda.plugin.v1.HookRequest
	4,  // 4: nilda.plugin.v1.PluginService.HandleEvent:input_type -> nilda.plugin.v1.EventRequest
	6,  // 5: nilda.plugin.v1.PluginService.Health:input_type -> nilda.plugin.v1.HealthRequest
	8,  // 6: nilda.plugin.v1.HostService.ContentSite:input_type -> nilda.plugin.v1.SiteRequest
	10, // 7: nilda.plugin.v1.HostService.ContentPageBySlug:input_type -> nilda.plugin.v1.PageBySlugRequest
	13, // 8: nilda.plugin.v1.HostService.ContentList:input_type -> nilda.plugin.v1.ContentListRequest
	16, // 9: nilda.plugin.v1.HostService.UserByID:input_type -> nilda.plugin.v1.UserByIDRequest
	18, // 10: nilda.plugin.v1.HostService.MediaByID:input_type -> nilda.plugin.v1.MediaByIDRequest
	20, // 11: nilda.plugin.v1.HostService.KVGet:input_type -> nilda.plugin.v1.KVGetRequest
	22, // 12: nilda.plugin.v1.HostService.KVSet:input_type -> nilda.plugin.v1.KVSetRequest
	24, // 13: nilda.plugin.v1.HostService.KVDel:input_type -> nilda.plugin.v1.KVDelRequest
	26, // 14: nilda.plugin.v1.HostService.KVIncr:input_type -> nilda.plugin.v1.KVIncrRequest
	28, // 15: nilda.plugin.v1.HostService.EmitEvent:input_type -> nilda.plugin.v1.EmitEventRequest
	1,  // 16: nilda.plugin.v1.PluginService.Init:output_type -> nilda.plugin.v1.InitResponse
	3,  // 17: nilda.plugin.v1.PluginService.HandleHook:output_type -> nilda.plugin.v1.HookResponse
	5,  // 18: nilda.plugin.v1.PluginService.HandleEvent:output_type -> nilda.plugin.v1.EventResponse
	7,  // 19: nilda.plugin.v1.PluginService.Health:output_type -> nilda.plugin.v1.HealthResponse
	9,  // 20: nilda.plugin.v1.HostService.ContentSite:output_type -> nilda.plugin.v1.Site
	11, // 21: nilda.plugin.v1.HostService.ContentPageBySlug:output_type -> nilda.plugin.v1.PageBySlugResponse
	15, // 22: nilda.plugin.v1.HostService.ContentList:output_type -> nilda.plugin.v1.ContentListResponse
	17, // 23: nilda.plugin.v1.HostService.UserByID:output_type -> nilda.plugin.v1.User
	19, // 24: nilda.plugin.v1.HostService.MediaByID:output_type -> nilda.plugin.v1.Media
	21, // 25: nilda.plugin.v1.HostService.KVGet:output_type -> nilda.plugin.v1.KVGetResponse
	23, // 26: nilda.plugin.v1.HostService.KVSet:output_type -> nilda.plugin.v1.KVSetResponse
	25, // 27: nilda.plugin.v1.HostService.KVDel:output_type -> nilda.plugin.v1.KVDelResponse
	27, // 28: nilda.plugin.v1.HostService.KVIncr:output_type -> nilda.plugin.v1.KVIncrResponse
	29, // 29: nilda.plugin.v1.HostService.EmitEvent:output_type -> nilda.plugin.v1.EmitEventResponse
	16, // [16:30] is the sub-list for method output_type
	2,  // [2:16] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_contract_plugin_proto_init() }
func file_contract_plugin_proto_init() {
	if File_contract_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_plugin_proto_rawDesc), len(file_contract_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_contract_plugin_proto_goTypes,
		DependencyIndexes: file_contract_plugin_proto_depIdxs,
		MessageInfos:      file_contract_plugin_proto_msgTypes,
	}.Build()
	File_contract_plugin_proto = out.File
	file_contract_plugin_proto_goTypes = nil
	file_contract_plugin_proto_depIdxs = nil
}
